### ISSUE TITLE
Meeting [Team Checkin]: Core Team Weekly 7th FEB 2022 - 0800 to 1000 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#121]
- [Meeting Link](https://us02web.zoom.us/meeting/register/tZ0rce2gpz0jEtYuDeM_NAB190InbIBRvG56): One-Time Registration is required. 
- Last Meeting: #118
- Next Meeting: #123 
- [C3ETH Team Calendar](https://calendar.google.com/calendar/embed?src=2g3h5vj0cui84imibn6bpa4tr4%40group.calendar.google.com&ctz=Etc%2FGMT)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)

### Attendees
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Andreas Sosilo (@andreassosilo) 
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)
- Tien Nguyen Anh (@tienna)
- Andy Sibuea (@zicozibu)
- Andre Cahyadi

### Apologies
- Robert O'Brien (@wolstaeb)
- Stephen Whitenstall (@stephen-rowan)
- Jack O'Brien (@PardusEidolon)
- Felix Weber (@FelixfromSwarm)
- Yuta Yuta (@cardanoz)

### Topics to cover

1. General catch-up with each other.
2. Townhall Recap & Catalyst Updates (if any)
3. Fund6 Proposal Specific Updates
4. (Add additional topics here)

#### Orbit & KPI Reporting
- We do have KPI on each of our proposals
- @wolstaeb is promoting this Orbit as system of reporting
- @A-W-G : concern about privacy

#### C3ETH Meetup & Zoom Registration
- We need to remove the Meetup registration and only use the Zoom registration
- @A-W-G : problem with C3ETH Meetup event in French language. We need to update the Meetup event to English
- Eastern Townhall Events meetings from Sat 12 Feb 2022 will be used Zoom link for new registration https://us02web.zoom.us/meeting/register/tZcqcOCopjsuGNd0IAZPoGfYNEYCXO_prtEd
- @andreassosilo : removed unnecessary Meetup event + update the upcoming event with the new Zoom registration link

#### Community Translation Document
-  @A-W-G : redundant to translate the previous Fund
- Budget? 1000 ADA

#### Catalyst Innovate

Jo Allum has offered to help out with starting to work on and pull together the Catalyst Innovate Programme. She will organise a working session for Catalyst Innovate.

#### Zoom Login Details

@PardusEidolon, @wolstaeb  @zicozibu and @Linh-LP  have Zoom login access now. Any of us can be zoom hosts. 

#### Working Sessions

Project Closeout, Zoom Settings and Calendar, Orbit & KPI Reporting Sessions. @wolstaeb was tied-up all of last week so was unable to organise the working sessions to do the project closeout, retrospective, and do a tutorial on Orbit. He will sort that out this week.

### Previous Meeting Action Items

Outline of Action Items. See meeting notes #118

- [x] 1. Moderator Programme (Felix) snd thoughts on Escalation.
- [x] 2. No-Code Bake-Off Session (English Breakout Room)
- [x] 3. Orbit & KPI Reporting Session (@wolstaeb) 
- [x] 4. A Session to get Zoom/Meetup/Calendar all configured and tested (@wolstaeb).
- [x] 5. Update Meetup Zoom Link in Meetup (@FelixfromSwarm ) #119 
- [X] 6. Pass Zoom Details to Lihn (@wolstaeb)
- [X] 7. Pass Ideascale Login Details to Andreas (@wolstaeb)
- [x] 8. Community Translation Document (for Yuta and Paul to understand)
- [x] 9. Translation Compensation - Move Ahead
- [x] 10. Discord House Keeping  (@YanTirta )
- [x] 11. Working Group Setup for Catalyst Innovate (@wolstaeb)
- [x] 12. A session for Fund6 Close Out (@Mietran0407, @YanTirta , @wolstaeb)
- [x] 13. Member Survey ( @YanTirta @Mietran0407 @YanTirta)
- [x] 14. Evolving the MiniIdefest Format (Name, Format)
- [x] 15. Live Interpreter - Arrange a session with Yuta, Yan, and the Interpreter to work out if/how things can work.
- [x] 16. How to help Mainroom English to Vietnamese, Japanese, Indonesian?
- [x] 17. Need to Promote the C3ETH Stakepool, and what needs to be done wrt. [Ryuuki Network](https://catalystswarm.com/pool-network/)
- [x] 18. Twitter Account Use via Tweet Deck - Please start using this account. #120 
- [ ] 19. Fund 8 Challenge Setting Reviews (Following Yuta’s Fund7 Review.)

**Comment by andrecahyadi** [comment]
Community Translation Document, https://github.com/C3ETH/c3eth.github.io/discussions/90

**Comment by andrecahyadi** [comment]
Apologized if I misheard the words or missed something from you guys. 
I categorized everybody's comments on each action item. 

8. Community Translation Document (for Yuta and Paul to understand)
9. Translation Compensation
- Tien: same translation compensation for every country (similar with CA compensation)
- Angela: doing translation process similar with the Cardano Developer's documentation
- Andreas: ambassador translation (US$ 0.02/word) for any type of documents. Keep the translation activities within the budget, which is currently only 1,000 ADA in total
- Linh: not really agree with the translation activities
- Yan: translation reward structure categorized into L, M, S, XS based on the complexities (f6-proposalonboardingeastasiatoday).
_Current translation focus:_ Catalyst funds
_Next focus:_ GitHub documents
**Next steps by Yan, Tien, Angela**: categorizing the funds into groups, which ones are L, M, S, XS with translation period of 12 months and need to agree on the rewards structure

11. Working Group Setup for Catalyst Innovate
- Yan: Catalyst Innovate is similar with Catalyst Boost and need everyone to be proactive in this initiative
- Angela: was invited to the Catalyst Boost

13. Member Survey
- Linh: format was created by Linh to be used on every Eastern Town Hall meeting, https://docs.google.com/forms/d/e/1FAIpQLSdvvvD-TmgNd4OdWhkke7ZTZDG-fmFStr961IdwZY5MDiQGNA/viewform

14. Mini Idea Fest Name & Format
- Tien: will come up with the new suggested name & format
- Angela: the main IdeaFest was not uploaded into YouTube by IOHK

16. How to help Mainroom English to Vietnamese, Japanese, Indonesian?
- Yan: this include on how to invite any Cardano project's people to come to Eastern Town Hall
- Linh: create the main schedule first and then decide on which week that project's people could come. (Extra: Linh will provide main townhall meeting slides every Thursday, so that it can be translated into each language for Saturday's Eastern Town Hall meeting. 

17. Need to Promote the C3ETH Stakepool, and what needs to be done wrt. [Ryuuki Network](https://catalystswarm.com/pool-network/)
- Linh: needs main Room to present C3ETH stake pool & be aware a lot of pools could have similar agenda
- Angela: need a lot of work to invite communities to stake to C3ETH stake pool and need to explain where the rewards will go. 
- Tien: needs breakout Room to present C3ETH stake pool. 
IOG & CF delegation cycle to stake pools happens every 3 months and we just need to register in order to get that delegation

19. Fund 8 Challenge Setting Reviews (Following Yuta’s Fund7 Review.) 
- ALL: no recollection from everyone about this action item

Other Topics:
- Linh: asked to create a proposal for Eastern Town Hall so any ideas or activities suggested in Eastern Town Hall could be funded from here
